### PR TITLE
Support sending custom commands via adapter.sendTo

### PR DESCRIPTION
**Pull request by AlCalzone**
Not tested yet!!! I'm going to report how it goes tonight.

### CODE REVIEW

**Comment by AlCalzone** [comment]
Included some fixes, works for me now. Also documented it in the readme.

**Comment by GermanBluefox** [comment]
It is interesting, which commands can I send. Do you have some link?

**Comment by AlCalzone** [comment]
Its in the existing readme ;)
https://github.com/ioBroker/ioBroker.mihome-vacuum#send-your-own-commands
=> https://github.com/MeisterTR/XiaomiRobotVacuumProtocol

**Comment by GermanBluefox** [comment]
:) Thank you.

**Pull request merged**
